### ISSUE TITLE
JDASocket Fatal Error: Received a channel that isn't text or voice

### ISSUE THREAD

**Issue by WTMike24** [jagrosh/Selfbot#59] opened 2017-09-12 20:40 UTC
I'm not really sure what I need to include here. I downloaded the latest version of the JAR, ran the run.command, and ended up with this error. I've had this working before, so something must have changed, but I have no idea what.

https://pastebin.com/9SHGUtb6

**Comment by TheMonitorLizard** [comment] 2017-09-12 20:54
This is due to the addition of channel categories.
It will be fixed next version.

**Comment by WTMike24** [comment] 2017-09-12 20:55
Do you have an ETA? I'm not trying to be pushy, just curious. Thanks for making such a great bot!

**Comment by TheMonitorLizard** [comment] 2017-09-12 20:56
I didn't make it, @jagrosh did.
And no, there is no ETA, just be patient

**Comment by WTMike24** [comment] 2017-09-12 20:56
Oh, sorry. I didn't see who replied, just that someone did. Thanks for letting me know!

**Comment by jagrosh** [comment] 2017-09-12 20:59
When you run the `about` command, what version is displayed?

**Comment by WTMike24** [comment] 2017-09-12 20:59
Where do I run the command?

**Comment by jagrosh** [comment] 2017-09-12 21:00
on any server with your copy of the bot

**Comment by WTMike24** [comment] 2017-09-12 21:00
The bot won't respond to me at all

**Comment by jagrosh** [comment] 2017-09-12 21:01
Then the issue isn't channel categories. What is the name of the jar you are running?

**Comment by WTMike24** [comment] 2017-09-12 21:01
JSelfBot.jar

**Comment by jagrosh** [comment] 2017-09-12 21:02
uh, none of the releases are called that

**Comment by jagrosh** [comment] 2017-09-12 21:02
They should be in the form JMusicBot-X.Y.Z.jar

**Comment by WTMike24** [comment] 2017-09-12 21:02
But that's what's on the releases page, I swear that's it

**Comment by WTMike24** [comment] 2017-09-12 21:02
https://github.com/jagrosh/Selfbot/tree/master/src/jselfbot

**Comment by jagrosh** [comment] 2017-09-12 21:03
Nevermind, I am incorrect, I thought this was my music bot repo

**Comment by TheMonitorLizard** [comment] 2017-09-12 21:03
jag please

**Comment by WTMike24** [comment] 2017-09-12 21:03
Haha, all good, any idea on what I need to do to help you with this?

**Comment by jagrosh** [comment] 2017-09-12 21:04
Nothing, just wait for the next release. Those warnings you see shouldn't actually affect the function of the bot though.

**Comment by WTMike24** [comment] 2017-09-12 21:04
Well it doesn't respond to me at all, so I'll just hope everything goes well in development

**Comment by TheMonitorLizard** [comment] 2017-09-12 21:05
have you tried being patient and letting the bot start up?
if you're on a lot of servers it can take a while to start

**Comment by WTMike24** [comment] 2017-09-12 21:08
See, now I feel really stupid. I swear it wasn't working, I gave it a good few minutes after it said `Type self.help in Discord to get started!` but it wasn't responding. Now it is, and I have no idea what happened. Sorry for bothering you guys with this, great work on the bot!

**Closed** 2017-09-12 21:11 UTC
